/**
 * Codex config.toml 生成
 *
 * codex 读 CODEX_HOME 下的 config.toml, 主要字段:
 *   - model            : 默认模型
 *   - model_provider   : 当前使用的 provider 名
 *   - [model_providers.<name>].base_url : OpenAI 兼容端点
 *   - [model_providers.<name>].wire_api : "responses" (codex 0.138 唯一允许值)
 *   - [model_providers.<name>].env_key  : 哪个 env 变量装 api key
 *   - [model_providers.<name>].requires_openai_auth : false 跳过 login
 *
 * 反代地址: 反代监听 127.0.0.1:<port>, 反代路径 /v1/responses,
 * 所以 codex 配置 base_url = http://127.0.0.1:<port>/v1.
 * codex 内部会请求 POST {base_url}/responses, 刚好对得上.
 *
 * 这里我们用临时目录 (process.cwd()/codex-tmp/<id>) 避免污染用户的 ~/.codex.
 */

import { mkdirSync, writeFileSync, rmSync } from 'fs'
import { join } from 'path'
import { randomBytes } from 'crypto'
import { createLogger } from '../../utils/logger.js'

const logger = createLogger('codex-config')

export interface CodexConfigOptions {
  /** 反代 base_url (e.g. http://127.0.0.1:51234) — codex 会拼 /v1/responses */
  proxyBaseUrl: string
  /** 实际供应商名字, 用于 [model_providers.<name>] 段 */
  providerName: string
  /** 显示在 codex UI 上的供应商描述 */
  providerDisplayName?: string
  /** env 变量名, codex 会从 env 里读 key. 我们 spawn 时设上 */
  apiKeyEnvVar?: string
  /** 默认 model, e.g. "gpt-5.4" */
  model?: string
  /** sandbox mode: 跟 process.ts 里的 spawn 参数保持一致 */
  sandbox?: 'read-only' | 'workspace-write' | 'danger-full-access'
  /** CODEX_HOME 根目录, 默认 process.cwd()/codex-tmp */
  parentDir?: string
  /** MCP servers 配置; 不传则默认添加 ComfyUI MCP server */
  mcpServers?: Array<{ name: string; url: string }>
}

export interface CodexConfigHandle {
  /** CODEX_HOME 路径, spawn codex 时塞到 env 即可 */
  codexHome: string
  /** 实际写盘的 config.toml 路径 */
  configPath: string
  /** 清理临时目录 */
  cleanup(): void
}

const DEFAULT_PROVIDER_NAME = process.env.CODEX_PROVIDER_NAME ?? 'sga'

// 默认的 ComfyUI MCP server URL.
// 很多 ComfyUI 部署并没有开启 /mcp 端点, 默认指向 8188/mcp 会导致 codex 启动时打印一串 MCP 失败错误.
// 这里加一个快速连通性探测: 如果目标 URL 返回 4xx/5xx, 就跳过这个 MCP server,
// codex 仍然可以正常对话 (只是少了一些 ComfyUI 工具).
const DEFAULT_COMFYUI_MCP_URL = process.env.CODEX_COMFYUI_MCP_URL ?? 'http://127.0.0.1:8188/mcp'
const DISABLE_COMFYUI_MCP = process.env.CODEX_DISABLE_COMFYUI_MCP === '1'

export async function writeCodexConfig(opts: CodexConfigOptions): Promise<CodexConfigHandle> {
  const tag = randomBytes(4).toString('hex')
  const codexHome = join(opts.parentDir ?? join(process.cwd(), 'codex-tmp'), `sga-${tag}`)
  mkdirSync(codexHome, { recursive: true })

  const provider = opts.providerName || DEFAULT_PROVIDER_NAME
  const apiKeyEnv = opts.apiKeyEnvVar ?? 'OPENAI_API_KEY'
  const sandbox = opts.sandbox ?? (process.env.CODEX_SANDBOX_MODE as 'read-only' | 'workspace-write' | 'danger-full-access' | undefined) ?? 'workspace-write'
  const model = opts.model ?? process.env.CODEX_DEFAULT_MODEL ?? 'gpt-5.4'

  const proxyBase = opts.proxyBaseUrl.replace(/\/$/, '')
  // 探测默认的 comfyui MCP server 是否真的存在;
  // 不存在/被禁用时, 不写入 [mcp_servers.comfyui] 段, 避免 codex 启动时报
  // "Transport channel closed, when UnexpectedContentType(... 405: Method Not Allowed)"
  // 这种吓人的错误日志.
  const mcpServers = opts.mcpServers && opts.mcpServers.length > 0
    ? opts.mcpServers
    : (DISABLE_COMFYUI_MCP
        ? []
        : await probeMcpServer({ name: 'comfyui', url: DEFAULT_COMFYUI_MCP_URL }))

  const mcpServersToml = mcpServers
    .map((s) => `
[mcp_servers.${escapeTomlString(s.name)}]
type = "streamable-http"
url = "${escapeTomlString(s.url)}"
`)
    .join('')

  const toml = `# Auto-generated by SGA Codex backend. Do not edit.
# 用于把 codex app-server 路由到 SGA 本地反代, 反代再转译到用户配置的供应商.

model = "${model}"
model_provider = "${provider}"
sandbox_mode = "${sandbox}"
approval_policy = "never"

[model_providers.${provider}]
name = "${escapeTomlString(opts.providerDisplayName ?? provider)}"
base_url = "${proxyBase}/v1"
wire_api = "responses"
env_key = "${apiKeyEnv}"
requires_openai_auth = false
${mcpServersToml}`

  const configPath = join(codexHome, 'config.toml')
  writeFileSync(configPath, toml, 'utf-8')
  logger.info(`wrote codex config: ${configPath}`)
  logger.debug(`toml=\n${toml}`)

  return {
    codexHome,
    configPath,
    cleanup: () => {
      try {
        rmSync(codexHome, { recursive: true, force: true })
      } catch (err) {
        logger.warn(`failed to cleanup codex home ${codexHome}: ${err instanceof Error ? err.message : String(err)}`)
      }
    },
  }
}

/** 简单转义: TOML 字符串里如果含 ", 换成 \" */
function escapeTomlString(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')
}

/**
 * 探测 MCP server 是否真的可连通 (HTTP HEAD).
 * 任何 4xx/5xx/timeout/连接拒绝 → 返回空数组, 调用方决定不写该 MCP 段.
 * 2xx/3xx → 返回原 server (认为可用).
 *
 * best-effort 探测, 3 秒超时, 失败不影响 codex 启动.
 */
async function probeMcpServer(
  server: { name: string; url: string },
): Promise<Array<{ name: string; url: string }>> {
  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), 3000)
  try {
    const resp = await fetch(server.url, {
      method: 'HEAD',
      signal: controller.signal,
    })
    if (resp.status >= 200 && resp.status < 400) {
      logger.info(`MCP server ${server.name} probe OK (status=${resp.status})`)
      return [server]
    }
    logger.warn(
      `MCP server ${server.name} not available (status=${resp.status}), ` +
      `skipping it in codex config.toml. Set CODEX_COMFYUI_MCP_URL to override.`,
    )
    return []
  } catch (err) {
    // 连接拒绝 / 超时 / DNS 失败 → 视为不可用
    const msg = err instanceof Error ? err.message : String(err)
    logger.info(
      `MCP server ${server.name} not reachable (${msg.slice(0, 100)}), ` +
      `skipping it in codex config.toml. ` +
      `Set CODEX_DISABLE_COMFYUI_MCP=1 to skip probe, or CODEX_COMFYUI_MCP_URL to override.`,
    )
    return []
  } finally {
    clearTimeout(timer)
  }
}
